### ISSUE TITLE
The Stat is not related to this page. change to this page

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/Opensource-practice#52]
![image](https://github.com/user-attachments/assets/f310082b-826c-49b1-84e1-8b6d49a9dae1)

**Comment by vansh-codes** [comment]
Hello @sanjay-kv, I can fix this issue

**Comment by vansh-codes** [comment]
Hello @sanjay-kv , the PR is automatically  merged and closed by the bot, I have fixed the issue
Please add relevant gssoc tags in the PR
PR link for easy access: #70
